name: James Beta
favicon: null
layout_spectrum: 0.6930685881525278
typography_spectrum: 0.32322
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#8b8e96'
    - '#fef200'
    - '#22b04b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
